# Generated by Django 3.2.9 on 2022-09-09 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('day_birth', models.DateField()),
                ('price', models.FloatField()),
                ('color', models.CharField(max_length=30)),
                ('male', models.BooleanField()),
                ('description', models.TextField(max_length=300)),
            ],
        ),
    ]
