# Generated by Django 3.2.9 on 2022-09-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
