# Generated by Django 3.2.9 on 2022-09-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_dog_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='price',
            field=models.FloatField(),
        ),
    ]
