# Generated by Django 3.2.9 on 2022-10-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_dog_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='id_image_drive',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
